// <auto-generated />
using System;
using Invoice.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Invoice.API.Migrations
{
    [DbContext(typeof(InvoiceDbContext))]
    partial class InvoiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Invoice.Core.Models.InvoiceLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InternalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ItemsDiscount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SalesTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalTaxableFees")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UnitType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ValueDifference")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("InvoiceLines");
                });

            modelBuilder.Entity("Invoice.Core.Models.Invoices", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateTimeIssued")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentTypeVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ExtraDiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("InternalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("NetAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProformaInvoiceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PurchaseOrderDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PurchaseOrderReference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesOrderDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesOrderReference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ServiceDeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TaxpayerActivityCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalItemsDiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalSalesAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("Invoice.Core.Models.TaxTotal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<string>("TaxType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("TaxTotals");
                });

            modelBuilder.Entity("Invoice.Core.Models.InvoiceLine", b =>
                {
                    b.HasOne("Invoice.Core.Models.Invoices", "Invoice")
                        .WithMany("InvoiceLines")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Invoice.Core.Models.Discount", "Discount", b1 =>
                        {
                            b1.Property<int>("InvoiceLineId")
                                .HasColumnType("int");

                            b1.Property<decimal?>("Amount")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal?>("Rate")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("InvoiceLineId");

                            b1.ToTable("InvoiceLines");

                            b1.WithOwner()
                                .HasForeignKey("InvoiceLineId");
                        });

                    b.OwnsMany("Invoice.Core.Models.TaxableItem", "TaxableItems", b1 =>
                        {
                            b1.Property<int>("InvoiceLineId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal>("Rate")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<string>("SubType")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("TaxType")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("InvoiceLineId", "Id");

                            b1.ToTable("TaxableItem");

                            b1.WithOwner()
                                .HasForeignKey("InvoiceLineId");
                        });

                    b.OwnsOne("Invoice.Core.Models.Value", "UnitValue", b1 =>
                        {
                            b1.Property<int>("InvoiceLineId")
                                .HasColumnType("int");

                            b1.Property<decimal>("AmountEGP")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal?>("AmountSold")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal?>("CurrencyExchangeRate")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<string>("CurrencySold")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("InvoiceLineId");

                            b1.ToTable("InvoiceLines");

                            b1.WithOwner()
                                .HasForeignKey("InvoiceLineId");
                        });

                    b.Navigation("Discount");

                    b.Navigation("Invoice");

                    b.Navigation("TaxableItems");

                    b.Navigation("UnitValue")
                        .IsRequired();
                });

            modelBuilder.Entity("Invoice.Core.Models.Invoices", b =>
                {
                    b.OwnsOne("Invoice.Core.Models.Issuer", "Issuer", b1 =>
                        {
                            b1.Property<int>("InvoicesId")
                                .HasColumnType("int");

                            b1.Property<string>("Id")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("InvoicesId");

                            b1.ToTable("Invoices");

                            b1.WithOwner()
                                .HasForeignKey("InvoicesId");

                            b1.OwnsOne("Invoice.Core.Models.IssuerAddress", "Address", b2 =>
                                {
                                    b2.Property<int>("IssuerInvoicesId")
                                        .HasColumnType("int");

                                    b2.Property<string>("AdditionalInformation")
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("BranchId")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("BuildingNumber")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Country")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Floor")
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Governate")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Landmark")
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("PostalCode")
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("RegionCity")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Room")
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Street")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("IssuerInvoicesId");

                                    b2.ToTable("Invoices");

                                    b2.WithOwner()
                                        .HasForeignKey("IssuerInvoicesId");
                                });

                            b1.Navigation("Address")
                                .IsRequired();
                        });

                    b.OwnsOne("Invoice.Core.Models.Receiver", "Receiver", b1 =>
                        {
                            b1.Property<int>("InvoicesId")
                                .HasColumnType("int");

                            b1.Property<string>("Id")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Name")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("InvoicesId");

                            b1.ToTable("Invoices");

                            b1.WithOwner()
                                .HasForeignKey("InvoicesId");

                            b1.OwnsOne("Invoice.Core.Models.ReceiverAddress", "Address", b2 =>
                                {
                                    b2.Property<int>("ReceiverInvoicesId")
                                        .HasColumnType("int");

                                    b2.Property<string>("AdditionalInformation")
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("BuildingNumber")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Country")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Floor")
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Governate")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Landmark")
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("PostalCode")
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("RegionCity")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Room")
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Street")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("ReceiverInvoicesId");

                                    b2.ToTable("Invoices");

                                    b2.WithOwner()
                                        .HasForeignKey("ReceiverInvoicesId");
                                });

                            b1.Navigation("Address");
                        });

                    b.Navigation("Issuer")
                        .IsRequired();

                    b.Navigation("Receiver")
                        .IsRequired();
                });

            modelBuilder.Entity("Invoice.Core.Models.TaxTotal", b =>
                {
                    b.HasOne("Invoice.Core.Models.Invoices", "Invoice")
                        .WithMany("TaxTotals")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("Invoice.Core.Models.Invoices", b =>
                {
                    b.Navigation("InvoiceLines");

                    b.Navigation("TaxTotals");
                });
#pragma warning restore 612, 618
        }
    }
}
